version: '3.5'

services:
    nginx:
        image: nginx:alpine
        volumes:
            - './../:/usr/share/nginx/html'
            - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
        links:
            - web
        ports:
            - '8080:80'

    web:
        build:
            context: './../'
            dockerfile: './.docker/web/Dockerfile'
        volumes:
            - './../:/code'

networks:
    learn-php:
        driver: bridge
        name: learn-php
